import Head from 'next/head';
import Icons from '../components/Icons';
import Messanger from '../components/Messanger';
import SideBar from '../components/SideBar';

export default function Home() {
  return (
    <div className="flex flex-row h-screen">
      <Head>
        <title>Thopz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Icons */}
      <Icons />

      {/* Listen */}
      <SideBar />

      {/* messages */}
      <Messanger />
    </div>
  );
}
